### ISSUE TITLE
Improve the SSH UX on errors

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#123]
Ref #121 
Make so that:
 - SSH retries a couple of times (e.g. 10 or similar), notifying the user every `n` seconds.
 - If the container is down, say that
 - If the IP isn't reachable (i.e. can't be pinged or similar), say that

probably more...

**Comment by twelho** [comment]
Also if the user shuts down the VM by issuing `reboot`, `ignite ssh` will throw an error. This might be difficult to fix properly though.

**Comment by twelho** [comment]
>If the container is down, say that

To this Ignite responds: `VM "<uid>" is not running`.

>If the IP isn't reachable (i.e. can't be pinged or similar), say that

If the VM hasn't got an IP accessible from outside (its network config is invalid),
Ignite responds: `VM "<uid>" has no usable IP addresses`.

Do these fulfill the requirements?

>SSH retries a couple of times (e.g. 10 or similar), notifying the user every n seconds.

This is hard to implement, as for each "remote command failure" SSH reports exit code 255 and both "connection failed" and "the user rebooted the VM" return that code and the same error message.

**Comment by twelho** [comment]
Leading to Ignite trying to reconnect to a rebooted VM, which is not what we want.

**Comment by twelho** [comment]
I fixed a bunch of other issues though regarding authentication and warnings/errors for a seamless experience, will open a PR soon.

If you want, I can make the connection timeout customizable via a flag (instead of the retries, which cannot be implemented due to `restart` being synonymous with `connection failure`)

**Comment by luxas** [comment]
> Do these fulfill the requirements?

For now, yes. If we find more stuff we want to improve later, then we'll do that.

> If you want, I can make the connection timeout customizable via a flag (instead of the retries, which cannot be implemented due to restart being synonymous with connection failure)

Sounds good :+1:

> Leading to Ignite trying to reconnect to a rebooted VM, which is not what we want.

Can't we know that as long as the VM object's status is `Running` it's meant to be running and ignite-spawn hasn't stopped it? Or check if the docker container is running? I'm just thinking out loud here, we should not do that kind of stuff for v0.4.1.

**Comment by twelho** [comment]
>Can't we know that as long as the VM object's status is Running it's meant to be running and ignite-spawn hasn't stopped it? Or check if the docker container is running?

The problem is that the VM is still `Running` while it's shutting down (rebooting), so `ignite ssh` will not know it's _supposed_ to be shutting down. We also have the issue of `ignite-spawn` and the CLI trying to read/write to the same file at the same time. Either we need some field indicating state transitions or just wait until have the communication in place between `ignite-spawn` and the CLI.

Either way, that's not for v0.4.1 like you said. All the other rework is now in https://github.com/weaveworks/ignite/pull/149.
