### ISSUE TITLE
Ignite should check if it has root privileges instead of if uid=0

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#137]
As reported by @arun-gupta

More a generic problem but this is stalling me from trying `ignite`
Created an EC2 Ubuntu instance, added `ubuntu` to `sudo` and `root` group but invoking `ignite version` still gives the error:

```
This program needs to run as root.
```

`sudo ignite version` works

Let's fix this for v0.4.1

**Comment by twelho** [comment]
Ignite currently needs to call `mount`, which requires UID to be 0. Adding the user to the `sudo` or `root` groups is unfortunately not enough, Ignite needs to be actually called with `sudo` or from a root shell to elevate privileges, which is why this check exists.

We could implement on-demand privilege checking (so that `version` wouldn't need root), but IMO that isn't very useful as the user will still need root access to perform pretty much anything else, including creating/managing VMs.

If/when we eventually have a daemon like Docker, we can have a specific group for Ignite that uses the daemon (running with UID 0) to perform these commands.

**Comment by arun-gupta** [comment]
So either all commands have to run as `sudo` or in a root shell?

**Comment by luxas** [comment]
> So either all commands have to run as sudo or in a root shell?

@arun-gupta For the time being, yes.
What is stopping you from using `sudo` or being root?

I had forgot about this (`call mount, which requires UID to be 0.`) when submitting the issue, thanks for reminding @twelho!

**Comment by luxas** [comment]
For context around this, Firecracker takes a block device to boot (and a kernel) as input. The block device could technically be a physical partition on a disk, or what we use, file-based block devices. Nevertheless, we somehow need to populate the block device partition with contents from the OCI images.

Since there is no common way to manipulate block devices directly; we mount the disk to a temporary directory, and copy over the contents. This requires root, as @twelho said. One way to work around this is by creating a dedicated `ignite` daemon, and some kind of socket between the client and the daemon, or similar interface (see issue #33). We aim to do this eventually, but at the moment it's out of scope due to the vast amount of work needed for the "new" problems that come with that (authentication, authorization, API negotiation skew, common interfaces, etc.).

With this in mind, I do not see us removing the dependency in at least a few weeks.

Still I would like to learn about your use-case/problem running with `sudo`. Nevertheless, regardless of if you install the `dockerd` or `kubelet` daemons, _they_ do need to run as root in turn, even though `kubectl` and `docker` doesn't have to.

**Comment by arun-gupta** [comment]
Adding a `sudo` at https://github.com/weaveworks/ignite/blob/master/docs/installation.md would solve the confusion. I documented the exact set of steps at http://arun-gupta.github.io/ignite-firecracker/

**Comment by luxas** [comment]
Ok, thank you. Can I close this issue (we have https://github.com/weaveworks/ignite/issues/24 for avoiding root for the client, in general)?

**Comment by arun-gupta** [comment]
Yes
