### ISSUE TITLE
Add a FAQ.md

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#147]
To collect frequently asked questions in order to easily reference those when people ask.

**Comment by kim3z** [comment]
Yes, I think this is a good idea! @luxas 

Based on Joe Beda's livestream "TGI Kubernetes 082: Weaveworks Ignite" a lot of people seem to wonder **why is docker (containers) needed/used?**

I have some questions too that might help you make this FAQ:
- how does my filesystem specified in Docker image end up in a firecracker VM?
- how does networking in ignite work since there are both containers and VM's?
- can this be used as a development environment for web developers? If the answer is yes, how?

I'm sure @luxas you have got a lot of questions already from people that have tested ignite, but maybe would could ask on twitter (or somewhere else) what people want to know about ignite, and based on that make this FAQ.
