### ISSUE TITLE
Write e2e test cases for ignite rm

### ISSUE THREAD

**Issue by chanwit** [weaveworks/ignite#392]

**Comment by stealthybox** [comment]
Depends on CI /w nested virt

Can accomplish with TravisCI as of recent changes: https://twitter.com/_AkihiroSuda_/status/1167336407779557376

Could also use GCP or AWS vm's spawned from CircleCI, but this would be more latent.

**Comment by bbros-dev** [comment]
We have a test cookbook setup with test-kitchen harness in which it would be simple to write e2e test cases.

I believe these could have avoided a lot of the existing broken/undocumented behavior.

The issue is the cost of firing them up using cloud providers - currently Digital Ocean - everytime the CI/CD prcess runs.  Of course this ensures behavior isn't broken as well as no regressions are introduced.

As soon as I port the current test to use JASON manfest rather than YAML it's status will 1.0-rc1.

Happy to join Monday's call if you want to discuss further
