### ISSUE TITLE
Installation instructions broken with 0.6.x release being latest

### ISSUE THREAD

**Issue by burningion** [weaveworks/ignite#496]
The installation instructions here don't work with `0.6.2` being the latest release.

Following instructions here:

https://ignite.readthedocs.io/en/stable/installation.html#downloading-the-binary

There are no binaries built for the `0.6.2` release, and hence, breaks the installation instructions. 

For anyone currently stuck on trying to install binaries, `0.5.5` seems to be the last binary release. 

So replace `export VERSION=v0.6.2` in the bash script with `export VERSION=v0.5.5` to get things installed properly.

**Comment by stealthybox** [comment]
Hi @burningion :wave: 
Thank you so much for reporting this, and documenting the workaround.
We appreciate this as maintainers and this issue is super useful for users.

We've been frustratingly silent on this issue, as it relates to a security embargo for a CVE that is now public.

Please see #500 for full details on how this happened.
Please comment there if you need v0.6.1 or v0.6.2 artifacts re-published.

You can now upgrade to v0.6.3 if you'd like.
Please note that there is a notable migration moving from v0.5.5 to v0.6.3 as it uses containerd+CNI by default instead of docker+docker-bridge.

**Comment by burningion** [comment]
Thanks for the great response @stealthybox!
