### ISSUE TITLE
Documentation: Which GOOS & GOARCH binaries are downloadable.

### ISSUE THREAD

**Issue by taqtiqa-mark** [weaveworks/ignite#520]
This arose in the context of writing specs/tests for a Chef cookbook targeting Ignite - to be released (MIT) once I have green tests....
Which of the `GOOS` and `GOARCH` pairs does WeaveWorks/Ignite-project **provide built binaries for**?  Where "provide" is one of `Current`, `Future`, `TBA`,`Never`.

[Go Source](https://golang.org/doc/install/source#environment):

Could a completed version of the following table be added to the documentation, in the installation section?

$GOOS | $GOARCH | Status |
-- | -- | -- |
   aix | ppc64 | |
   android | 386 | |
   android | amd64 | |
   android | arm | |
   android | arm64 | |
   darwin | 386 | |
   darwin | amd64 | |
   darwin | arm | |
   darwin | arm64 | |
   dragonfly | amd64 | |
   freebsd | 386 | |
   freebsd | amd64 | |
   freebsd | arm | |
   illumos | amd64 | |
   js | wasm | |
   linux | 386 | |
   linux | amd64 | |
   linux | arm | |
   linux | arm64 | |
   linux | ppc64 | |
   linux | ppc64le | |
   linux | mips | |
   linux | mipsle | |
   linux | mips64 | |
   linux | mips64le | |
   linux | s390x | |
   netbsd | 386 | |
   netbsd | amd64 | |
   netbsd | arm | |
   openbsd | 386 | |
   openbsd | amd64 | |
   openbsd | arm | |
   openbsd | arm64 | |
   plan9 | 386 | |
   plan9 | amd64 | |
   plan9 | arm | |
   solaris | amd64 | |
   windows | 386 | |
   windows | amd64 | |

**Comment by stealthybox** [comment]
Thanks @taqtiqa-mark.
At the moment ignite only runs on `linux`. This is because of Firecracker's dependency on KVM.

Since 0.5.0, we've always released `amd64` and `arm64` builds:
https://github.com/weaveworks/ignite/releases

KVM has been ported before to other platforms.
There are many other ways to run virt on other platforms.
Ignite currently has no pluggable backend for supporting them.
@luxas has mentioned the idea of writing a QEMU interface, but there are no immediate plans.

The short answer is:
- linux amd64
- linux arm64

This is documented in our install guide:
https://ignite.readthedocs.io/en/stable/installation.html#system-requirements

**Comment by taqtiqa-mark** [comment]
OK so all other entries are 'Not planned'?

**Comment by stealthybox** [comment]
@taqtiqa-mark yep :+1:
