### ISSUE TITLE
Archlinux AUR distribution

### ISSUE THREAD

**Issue by techknowlogick** [weaveworks/ignite#765]
I've just packaged ignite(d) for archlinux via their AUR package repository. More info here: https://aur.archlinux.org/packages/ignite/

**Comment by stealthybox** [comment]
@techknowlogick thanks for adding this to the AUR!

Would you want to PR our install docs mentioning pacman/Arch support and the necessary install commands?

@darkowlzz and I looked at some PKGBUILDS and it looks like AUR does support building from a cached/persistent git-repo.
That could be a good alternative to just downloading the tarball.

Also, for our next tag, we've fixed that `*-dirty` ldflags issue you ran into [in the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ignite#n22).
If you're still building from tar, this should just work now:
```shell
make GIT_VERSION=v0.9.0 ignite ignited
make GIT_VERSION=v0.9.0 ignite ignited
```

We recommend building from git so that users get the proper commit information in `ignite version`, and it's supported directly by `PKGBUILD` and AUR sources.
