### ISSUE TITLE
Failed to open netns "/proc/24720/ns/net": failed to Statfs "/proc/24720/ns/net" & Timeout waiting for ignite-spawn startup

### ISSUE THREAD

**Issue by pbajno** [weaveworks/ignite#790]
Maybe somebody else will also have this problem. 

```
ERRO[0015] failed to setup network for namespace "ignite-6d08e202f7f44e1c": failed to open netns "/proc/24720/ns/net": failed to Statfs "/proc/24720/ns/net": no such file or directory 
FATA[0015] failed to open netns "/proc/24720/ns/net": failed to Statfs "/proc/24720/ns/net": no such file or directory 
```

![image](https://user-images.githubusercontent.com/18303501/109539116-99116000-7ac9-11eb-84a2-3842a10dde64.png)

So I found solution from stack overflow https://stackoverflow.com/questions/31265993/docker-networking-namespace-not-visible-in-ip-netns-list

`sudo ln -s /var/run/docker/netns  /var/run/netns `

But then again I got this. I had previously installed cni for some kubernetes experiments on my arm machine:

```
INFO[0008] Started Firecracker VM "dadda576cabfa738" in a container with ID "ignite-dadda576cabfa738" 
FATA[0018] timeout waiting for ignite-spawn startup
``` 

![image](https://user-images.githubusercontent.com/18303501/109539385-ec83ae00-7ac9-11eb-93e8-78c07dc9c984.png)

Any idea how to solve it?

**Comment by darkowlzz** [comment]
Hi @pbajno , thanks for sharing about the above issue.
Regarding the ignite-spawn startup failure, can you share more information about it by running ignite run with `--log-level=trace`? Hopefully the trace logs will help us know what failed.

**Comment by pbajno** [comment]
Nothing new here 
![image](https://user-images.githubusercontent.com/18303501/109543817-74b88200-7acf-11eb-8021-c840e850b112.png)

**Comment by darkowlzz** [comment]
I've seen similar issues when there's a mismatch between the ignite cli version and the sandbox (ignite-spawn) version. Since you reported using the `dev` sandbox in #788, there's a possibility that you built the ignite cli from the master branch and using the sandbox image v0.8.0. If that's true, the failure is because the latest ignite cli is using a different VM API that v0.8.0 sandbox is incompatible with. You can download v0.8.0 ignite cli binary for arm from [github release](https://github.com/weaveworks/ignite/releases/tag/v0.8.0) and see if that works.
If you want to try the latest, run `make` and build a `dev` sandbox image and use it.

**Comment by pbajno** [comment]
Okay, it worked so then we close it.
